// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getAppVersion() => RustLib.instance.api.crateApiGetAppVersion();

/// Initialise the persistent store.
///
/// Must be called once on app startup **before** taking orders or sending
/// invoices.  On native platforms pass the absolute path to the SQLite file
/// (e.g. `<app_documents_dir>/mostro.db`).  On WASM `path` is used as the
/// IndexedDB database name.
///
/// Subsequent calls are no-ops.
Future<void> initDb({required String path}) =>
    RustLib.instance.api.crateApiInitDb(path: path);
