import 'dart:async';

import 'package:clock/clock.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';

import 'package:mostro/core/app_routes.dart';
import 'package:mostro/core/app_theme.dart';
import 'package:mostro/core/automation/automation_id.dart';
import 'package:mostro/core/automation/automation_ids.dart';
import 'package:mostro/core/daemon_errors.dart';
import 'package:mostro/core/invoice_palette.dart';
import 'package:mostro/features/about/providers/mostro_node_provider.dart';
import 'package:mostro/features/order/models/invoice_rules.dart';
import 'package:mostro/features/order/providers/invoice_providers.dart';
import 'package:mostro/features/order/providers/trade_state_provider.dart';
import 'package:mostro/features/order/widgets/invoice_clock.dart';
import 'package:mostro/features/order/widgets/invoice_widgets.dart';
import 'package:mostro/features/settings/providers/nwc_provider.dart';
import 'package:mostro/features/trades/providers/trades_providers.dart'
    show refreshTrades, tradeInfoProvider;
import 'package:mostro/l10n/app_localizations.dart';
import 'package:mostro/shared/providers/peer_nym_provider.dart';
import 'package:mostro/shared/widgets/nwc_invoice_widget.dart';
import 'package:mostro/shared/widgets/peer_reputation_card.dart';
import 'package:mostro/shared/widgets/platform_aware_qr_scanner.dart';
import 'package:mostro/shared/widgets/redesign_app_bar.dart';
import 'package:mostro/src/rust/api/orders.dart' as orders_api;
import 'package:mostro/src/rust/api/types.dart'
    show OrderStatus, TradeInfo, TradeUpdate;

/// 13a · Receive your sats — Route `/add_invoice/:orderId`.
///
/// The buyer gives the invoice (or Lightning address) the sats are paid to.
/// One screen whether the buyer took the order or someone took theirs.
/// With NWC connected the invoice is generated by the wallet instead.
class AddLightningInvoiceScreen extends ConsumerStatefulWidget {
  const AddLightningInvoiceScreen({
    super.key,
    required this.orderId,
    this.amountSats,
    this.generateInvoice,
    this.submitInvoice,
  });

  final String orderId;

  /// Sats amount for the invoice. `null` until the trade provider resolves it.
  final int? amountSats;

  /// Test seam forwarded to [NwcInvoiceWidget]; production leaves it null so
  /// the widget generates the invoice over NWC. See [NwcInvoiceWidget].
  @visibleForTesting
  final Future<String> Function(int amountSats)? generateInvoice;

  /// Test seam for the submission itself; production sends the invoice to
  /// the daemon through the bridge and waits for its verdict.
  @visibleForTesting
  final Future<void> Function(String orderId, String invoice, BigInt sats)?
  submitInvoice;

  @override
  ConsumerState<AddLightningInvoiceScreen> createState() =>
      _AddLightningInvoiceScreenState();
}

class _AddLightningInvoiceScreenState
    extends ConsumerState<AddLightningInvoiceScreen>
    with InvoiceClock {
  /// Live validation waits this long after the last keystroke.
  static const _debounce = Duration(milliseconds: 300);

  final _invoiceController = TextEditingController();
  final _focus = FocusNode();
  bool _submitting = false;

  /// `true` while a protocol cancel is in flight — blocks re-entry and submit.
  bool _canceling = false;

  /// `true` when NWC is connected but generation failed → show manual form.
  bool _manualMode = false;

  /// One-shot guard so we don't navigate twice as further updates stream in.
  bool _navigated = false;

  /// The daemon's verdict on the last submission when it was a rejection.
  /// Kept on screen (a snackbar alone is gone in seconds) until the next
  /// submission, so the user can see why the invoice was refused and fix it.
  String? _lastError;

  Timer? _decodeTimer;

  /// The input [_decoded] belongs to; a different input is still pending.
  String? _decodedInput;
  DecodedInvoice? _decoded;

  /// False once the local decoder failed to run: invoices go to the daemon
  /// unjudged rather than being refused for a missing bridge.
  bool _decoderAvailable = true;

  @override
  void initState() {
    super.initState();
    _focus.addListener(() => setState(() {}));
    ref.listenManual<AsyncValue<int?>>(
      invoiceDeadlineProvider(widget.orderId),
      (_, next) => trackInvoiceDeadline(next.valueOrNull),
      fireImmediately: true,
    );
  }

  @override
  void dispose() {
    _decodeTimer?.cancel();
    _invoiceController.dispose();
    _focus.dispose();
    super.dispose();
  }

  BigInt? _resolvedSats(WidgetRef ref) {
    final fromProvider =
        ref.watch(tradeAmountProvider(widget.orderId)).valueOrNull;
    if (fromProvider != null) return fromProvider;
    final fallback = widget.amountSats;
    return fallback != null ? BigInt.from(fallback) : null;
  }

  String get _input => normalizeInvoiceInput(_invoiceController.text);

  void _onInputChanged() {
    _decodeTimer?.cancel();
    setState(() {});
    final input = _input;
    if (classifyInvoiceInput(input) != InvoiceInputKind.bolt11) return;
    _decodeTimer = Timer(_debounce, () => _decode(input));
  }

  Future<void> _decode(String input) async {
    DecodedInvoice? decoded;
    var available = true;
    try {
      decoded = await ref.read(invoiceDecoderProvider)(input);
    } catch (e) {
      debugPrint('[AddLightningInvoiceScreen] decoder unavailable: $e');
      available = false;
    }
    if (!mounted || input != _input) return;
    setState(() {
      _decodedInput = input;
      _decoded = decoded;
      _decoderAvailable = available;
    });
  }

  InvoiceCheck _check(BigInt? sats) {
    final input = _input;
    final pending =
        classifyInvoiceInput(input) == InvoiceInputKind.bolt11 &&
        _decoderAvailable &&
        _decodedInput != input;
    // While the decoder has not caught up, say nothing and hold submission.
    if (pending) return const InvoiceCheckPending();
    return checkInvoiceInput(
      raw: input,
      expectedSats: sats?.toInt(),
      decoded: _decoded,
      decoderAvailable: _decoderAvailable,
      // The same clock as the countdown, so the two never disagree.
      now: clock.now().millisecondsSinceEpoch ~/ 1000,
    );
  }

  bool _canSubmit(BigInt? sats) {
    if (_canceling) return false;
    final check = _check(sats);
    // A Lightning address is resolved with the trade amount, so it waits
    // for it.
    if (check is InvoiceCheckAddress && sats == null) return false;
    return invoiceCheckAllowsSubmit(check);
  }

  /// Cancel = cancel the trade itself (confirmed via dialog), not just leave
  /// the screen — going back is what lands on trade detail (#268).
  Future<void> _cancelOrder() async {
    // Serialize state-changing requests: no cancel while a submit or another
    // cancel is in flight (review round 1).
    if (_submitting || _canceling) return;
    final l10n = AppLocalizations.of(context);
    final confirmed = await showDialog<bool>(
      context: context,
      builder:
          (ctx) => AlertDialog(
            title: Text(l10n.cancelTradeDialogTitle),
            // This screen only exists before the trade goes active, where
            // mostrod cancels at once — no cooperative request.
            content: Text(l10n.cancelTradeDialogContentNotStarted),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx, false),
                child: Text(l10n.noButtonLabel),
              ),
              FilledButton(
                onPressed: () => Navigator.pop(ctx, true),
                child: Text(l10n.yesCancelButtonLabel),
              ).withAutomationId(AutomationIds.tradeCancelConfirm),
            ],
          ),
    );
    if (!mounted || confirmed != true) return;
    setState(() => _canceling = true);
    try {
      await orders_api.cancelOrder(orderId: widget.orderId);
      if (!mounted) return;
      _navigated = true;
      refreshTrades(ref);
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(l10n.cancelRequestSent)));
      context.go(AppRoute.home);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            localizedDaemonError(l10n, e, fallback: l10n.cancelRequestFailed),
          ),
        ),
      );
    } finally {
      if (mounted) setState(() => _canceling = false);
    }
  }

  Future<void> _submit(WidgetRef ref) async {
    if (_submitting || _canceling) return;
    final input = _input;
    // For Lightning Addresses, the sats amount must be resolved before sending —
    // the Rust side uses it to resolve the address. Bolt11 invoices encode
    // their own amount so BigInt.one is an acceptable non-zero placeholder.
    final resolvedSats = _resolvedSats(ref);
    if (classifyInvoiceInput(input) == InvoiceInputKind.address &&
        resolvedSats == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).waitingForTradeAmount),
        ),
      );
      return;
    }
    final sats = resolvedSats ?? BigInt.one;
    setState(() {
      _submitting = true;
      _lastError = null;
    });

    try {
      final submit = widget.submitInvoice ?? _bridgeSubmit;
      await submit(widget.orderId, input, sats);

      if (!mounted) return;
      context.go(AppRoute.tradeDetailPath(widget.orderId));
    } catch (e) {
      if (!mounted) return;
      // sendInvoice now waits for the daemon's reply: an error means the
      // invoice was NOT accepted (CantDo, e.g. invalid invoice, or timeout),
      // so stay on this screen. Strip the Rust error prefix for readability.
      final raw = e.toString();
      final anyhowMatch = RegExp(
        r'^.*?AnyhowException\((.+)\)$',
      ).firstMatch(raw);
      final msg = anyhowMatch != null ? anyhowMatch.group(1)! : raw;
      final display = localizedDaemonError(
        AppLocalizations.of(context),
        msg,
        fallback: msg,
      );
      setState(() => _lastError = display);
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(display)));
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  static Future<void> _bridgeSubmit(
    String orderId,
    String invoice,
    BigInt sats,
  ) => orders_api.sendInvoice(
    orderId: orderId,
    invoiceOrAddress: invoice,
    amountSats: sats,
  );

  Future<void> _paste() async {
    final data = await Clipboard.getData(Clipboard.kTextPlain);
    if (!mounted) return;
    final text = normalizeInvoiceInput(data?.text ?? '');
    if (text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).clipboardEmptyError),
        ),
      );
      return;
    }
    _setInput(text);
  }

  Future<void> _scan() async {
    final scanned = await Navigator.of(context).push<String>(
      MaterialPageRoute(
        builder: (routeContext) {
          final l10n = AppLocalizations.of(routeContext);
          return Scaffold(
            backgroundColor: OrderBookPalette.of(routeContext).bg,
            appBar: redesignAppBar(
              routeContext,
              title: l10n.scanQrCodeTitle,
              onBack: () => Navigator.of(routeContext).pop(),
            ),
            body: PlatformAwareQrScanner(
              hint: l10n.invoiceFieldHint,
              onDetected: (value) => Navigator.of(routeContext).pop(value),
            ),
          );
        },
      ),
    );
    if (!mounted || scanned == null) return;
    _setInput(normalizeInvoiceInput(scanned));
  }

  void _setInput(String text) {
    _invoiceController.value = TextEditingValue(
      text: text,
      selection: TextSelection.collapsed(offset: text.length),
    );
    _onInputChanged();
  }

  /// The daemon's verdict on the last refused submission, as a readout
  /// (`invoice.error`) that stays until the next submission; nothing when
  /// there is none.
  Widget? _errorReadout() {
    final error = _lastError;
    if (error == null) return null;
    return InvoiceValidationRow(
      text: error,
      isValid: false,
    ).withAutomationId(AutomationIds.invoiceError, label: error);
  }

  /// Leave the screen when mostrod cancels the order (e.g. the buyer let the
  /// waiting-state window expire): the daemon ignores messages for a
  /// canceled order, so without this the form just sits here and every
  /// submit dies with a 10s NoDaemonResponse.
  void _listenForCancellation(AppLocalizations l10n) {
    ref.listen<AsyncValue<TradeUpdate>>(tradeUpdatesProvider, (prev, next) {
      final update = next.valueOrNull;
      if (update == null || _navigated || !mounted) return;
      if (update.orderId != widget.orderId) return;
      switch (update.status) {
        case OrderStatus.canceled:
        case OrderStatus.cooperativelyCanceled:
        case OrderStatus.canceledByAdmin:
        case OrderStatus.expired:
          _navigated = true;
          // The wiped trade must also disappear from the My Trades cache.
          refreshTrades(ref);
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text(l10n.orderNoLongerActive)));
          context.go(AppRoute.home);
        default:
          break;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final book = OrderBookPalette.of(context);
    final isWalletConnected = ref.watch(isWalletConnectedProvider);
    final canPop = Navigator.of(context).canPop();
    final appBar = InvoiceAppBar(
      title: l10n.invoiceReceiveTitle,
      orderId: widget.orderId,
      orderIdAutomationId: AutomationIds.invoiceOrderId,
      copiedMessage: l10n.invoiceOrderIdCopied,
      onBack: canPop ? () => Navigator.of(context).maybePop() : null,
    );

    _listenForCancellation(l10n);

    // Resolve sats: provider first (live polling), fall back to constructor param.
    final sats = _resolvedSats(ref);

    // Counterpart (taker) reputation: the maker is the buyer here (adding an
    // invoice), so the taker is the seller (#305). Read via tradeInfoProvider,
    // which refreshes on the TradeUpdate emitted after the snapshot persists.
    final trade = ref.watch(tradeInfoProvider(widget.orderId)).valueOrNull;

    // When NWC is connected, we need the sats amount to auto-generate an invoice.
    // Show a loading indicator only in that case. Manual entry is always available.
    if (isWalletConnected && sats == null && !_manualMode) {
      return Scaffold(
        backgroundColor: book.bg,
        appBar: appBar,
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const CircularProgressIndicator(),
              const SizedBox(height: AppSpacing.md),
              Text(
                l10n.fetchingTradeAmount,
                style: TextStyle(color: book.textSecondary),
              ),
              const SizedBox(height: AppSpacing.md),
              TextButton(
                onPressed: () => setState(() => _manualMode = true),
                child: Text(l10n.enterInvoiceManually),
              ).withAutomationId(AutomationIds.invoiceManual),
            ],
          ),
        ),
      );
    }

    // If NWC wallet is connected, amount is known, and we haven't fallen back
    // to manual, show the auto-invoice widget instead of the manual form.
    if (isWalletConnected &&
        !_manualMode &&
        sats != null &&
        sats > BigInt.zero) {
      final error = _errorReadout();
      return Scaffold(
        backgroundColor: book.bg,
        appBar: appBar,
        body: Padding(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: Column(
            children: [
              // The maker must see who took their order even when NWC
              // auto-generates the invoice and the flow can proceed on its
              // own — that is exactly where the decision matters most (#305).
              if (trade?.peerRating != null) ...[
                PeerReputationCard(
                  rating: trade!.peerRating!,
                  reviews: trade.peerReviews ?? 0,
                  days: trade.peerDays ?? 0,
                  counterpartIsBuyer: false,
                ),
                const SizedBox(height: AppSpacing.lg),
              ],
              Expanded(
                child: Center(
                  child: NwcInvoiceWidget(
                    amountSats: sats.toInt(),
                    generateInvoice: widget.generateInvoice,
                    onInvoiceConfirmed: (invoice) {
                      _invoiceController.text = invoice;
                      _submit(ref);
                    },
                    onFallbackToManual:
                        () => setState(() => _manualMode = true),
                  ),
                ),
              ),
              // A generated invoice the daemon refuses needs the same
              // persistent reason as a typed one.
              if (error != null) ...[
                const SizedBox(height: AppSpacing.md),
                error,
                // The readout tells the buyer to add a new invoice, but this
                // branch has no form — its only other way out is leaving and
                // reopening the screen, which regenerates and resubmits the
                // wallet's (equally refused) invoice. Offer manual entry.
                const SizedBox(height: AppSpacing.md),
                TextButton(
                  onPressed: () => setState(() => _manualMode = true),
                  child: Text(l10n.enterInvoiceManually),
                ).withAutomationId(AutomationIds.invoiceManual),
              ],
            ],
          ),
        ),
      );
    }

    return Scaffold(
      backgroundColor: book.bg,
      // The keyboard must not cover the validation row, which sits right
      // under the field rather than in the footer.
      resizeToAvoidBottomInset: true,
      appBar: appBar,
      body: LayoutBuilder(
        builder:
            (context, constraints) => SingleChildScrollView(
              // #267: bottom system-bar inset so the footer clears the
              // gesture / 3-button navigation bar.
              padding: EdgeInsets.fromLTRB(
                kInvoiceGutter,
                4,
                kInvoiceGutter,
                kInvoiceGutter + MediaQuery.of(context).viewPadding.bottom,
              ),
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: constraints.maxHeight - 4 - kInvoiceGutter,
                ),
                child: IntrinsicHeight(child: _form(l10n, sats, trade)),
              ),
            ),
      ),
    );
  }

  Widget _form(AppLocalizations l10n, BigInt? sats, TradeInfo? trade) {
    final check = _check(sats);
    final error = _errorReadout();
    final validation = _validationText(l10n, check);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Sats amount calculated by the daemon (arrives in the take /
        // add-invoice reply and lands in the trade record).
        if (sats != null) ...[
          InvoiceHeroCard(
            label: l10n.invoiceYouReceiveLabel,
            sats: sats.toInt(),
            semanticsLabel: l10n.invoiceReceiveSemantics(sats.toString()),
            contextLine: _heroContext(l10n, trade),
            automationId: AutomationIds.invoiceAmount,
            automationLabel: sats.toString(),
          ),
          const SizedBox(height: 12),
        ],
        ValueListenableBuilder<Duration?>(
          valueListenable: invoiceRemaining,
          builder:
              (context, remaining, _) =>
                  remaining == null
                      ? const SizedBox.shrink()
                      : Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: InvoiceTimeBand(
                          remaining: remaining,
                          sentence: l10n.invoiceTimeToSend,
                        ),
                      ),
        ),
        _invoiceField(l10n),
        if (error != null) ...[
          const SizedBox(height: 8),
          error,
        ] else if (validation != null) ...[
          const SizedBox(height: 8),
          InvoiceValidationRow(
            text: validation,
            isValid: check is! InvoiceCheckError,
          ),
        ],
        if (trade != null) ...[
          const SizedBox(height: 12),
          InvoiceCounterpartCard(rows: _counterpartRows(l10n, trade)),
        ],
        const Spacer(),
        const SizedBox(height: 16),
        InvoicePrimaryButton(
          icon: Icons.bolt,
          label: l10n.invoiceSendButton,
          busy: _submitting,
          onPressed: _canSubmit(sats) ? () => _submit(ref) : null,
        ).withAutomationId(AutomationIds.invoiceSubmit),
        const SizedBox(height: 4),
        InvoiceCancelLink(
          label: l10n.invoiceCancelTrade,
          danger: false,
          onPressed: (_submitting || _canceling) ? null : _cancelOrder,
        ).withAutomationId(AutomationIds.invoiceCancel),
      ],
    );
  }

  Widget _invoiceField(AppLocalizations l10n) {
    final book = OrderBookPalette.of(context);
    final pal = InvoicePalette.of(context);
    return AnimatedContainer(
      duration: const Duration(milliseconds: 150),
      padding: const EdgeInsets.fromLTRB(16, 4, 4, 14),
      decoration: BoxDecoration(
        color: book.surface,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
          color: _focus.hasFocus ? pal.fieldFocusBorder : pal.cardBorder,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  l10n.invoiceFieldLabel.toUpperCase(),
                  style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0.66,
                    color: book.textSecondary,
                  ),
                ),
              ),
              InvoiceIconAction(
                icon: Icons.content_paste,
                tooltip: l10n.pasteButtonLabel,
                onPressed: _paste,
              ),
              InvoiceIconAction(
                icon: Icons.qr_code_scanner,
                tooltip: l10n.scanQrButtonLabel,
                onPressed: _scan,
              ),
            ],
          ),
          Padding(
            padding: const EdgeInsets.only(right: 12),
            child: TextField(
              controller: _invoiceController,
              focusNode: _focus,
              minLines: 1,
              maxLines: 4,
              autocorrect: false,
              enableSuggestions: false,
              enableIMEPersonalizedLearning: false,
              keyboardType: TextInputType.visiblePassword,
              cursorColor: book.lime,
              cursorWidth: 1.5,
              cursorHeight: 17,
              decoration: InputDecoration(
                // The value sits on the card itself: none of the theme's
                // fill or underline.
                isDense: true,
                filled: false,
                contentPadding: EdgeInsets.zero,
                border: InputBorder.none,
                enabledBorder: InputBorder.none,
                focusedBorder: InputBorder.none,
                hintText: l10n.invoiceFieldHint,
                hintStyle: TextStyle(
                  fontFamily: AppFonts.figures,
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                  color: book.textTertiary,
                ),
              ),
              style: TextStyle(
                fontFamily: AppFonts.figures,
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: book.textPrimary,
              ),
              onChanged: (_) => _onInputChanged(),
            ).withAutomationId(AutomationIds.invoiceText),
          ),
        ],
      ),
    );
  }

  /// The validation row's sentence, or null when the row is not drawn.
  String? _validationText(
    AppLocalizations l10n,
    InvoiceCheck check,
  ) => switch (check) {
    InvoiceCheckNone() ||
    InvoiceCheckPending() ||
    InvoiceCheckUnverified() => null,
    InvoiceCheckAddress() => l10n.invoiceValidAddress,
    InvoiceCheckValid(:final sats) => l10n.invoiceValidInvoice(
      formatInvoiceSats(sats),
    ),
    InvoiceCheckError(:final problem, :final actualSats, :final expectedSats) =>
      switch (problem) {
        InvoiceProblem.wrongAmount => l10n.invoiceErrorWrongAmount(
          formatInvoiceSats(actualSats ?? 0),
          formatInvoiceSats(expectedSats ?? 0),
        ),
        InvoiceProblem.expired => l10n.invoiceErrorExpired,
        InvoiceProblem.malformed => l10n.invoiceErrorMalformed,
        InvoiceProblem.unrecognized => l10n.invoiceErrorUnrecognized,
      },
  };

  /// `≈ 312 ARS · Bitcoin Bolivia`: what the sats are worth, and the node
  /// that settles the trade (not the counterpart).
  String? _heroContext(AppLocalizations l10n, TradeInfo? trade) {
    final fiat = trade == null ? null : formatInvoiceFiat(l10n, trade);
    final node = ref.watch(activeNodeNameProvider);
    final parts = [if (fiat != null) '≈ $fiat', if (node != null) node];
    return parts.isEmpty ? null : parts.join(' · ');
  }

  List<InvoiceCardRow> _counterpartRows(
    AppLocalizations l10n,
    TradeInfo trade,
  ) {
    final fiat = formatInvoiceFiat(l10n, trade);
    final method = trade.order.paymentMethod.trim();
    return [
      invoiceCounterpartRow(ref, l10n, trade, l10n.invoiceSellerLabel),
      if (fiat != null)
        (
          label: l10n.invoiceYouPayLabel,
          value: method.isEmpty ? fiat : '$fiat · $method',
          trailing: null,
        ),
    ];
  }
}

/// `312 ARS`, or null when the trade carries no fiat amount.
String? formatInvoiceFiat(AppLocalizations l10n, TradeInfo trade) {
  final amount = trade.order.fiatAmount;
  if (amount == null || amount <= 0) return null;
  final formatted = NumberFormat.decimalPatternDigits(
    locale: l10n.localeName,
    decimalDigits: amount == amount.truncateToDouble() ? 0 : 2,
  ).format(amount);
  return '$formatted ${trade.order.fiatCode}';
}

/// The counterpart's pseudonym, with their reputation beside it once the
/// daemon's snapshot has arrived.
InvoiceCardRow invoiceCounterpartRow(
  WidgetRef ref,
  AppLocalizations l10n,
  TradeInfo trade,
  String label,
) {
  final pubkey = trade.counterpartyPubkey;
  final handle =
      pubkey.isEmpty
          ? null
          : ref.watch(peerNymProvider(pubkey)).valueOrNull?.pseudonym;
  final hasSnapshot = trade.peerRating != null;
  return (
    label: label,
    value: handle ?? l10n.unknownPeerHandle,
    trailing:
        hasSnapshot
            ? counterpartStars(trade.peerRating, trade.peerReviews) ??
                l10n.invoiceNoTrades
            : null,
  );
}
