// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `bond_store`, `claim_for_order`, `claim_tx`, `emit_bond_slashed`, `emit_claim_update`, `infer_slash_cause`, `persist_claim`, `persist_retained_nodes`, `refresh_claim_nodes`, `retain_previous_node`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BondStore`

/// The active node's advertised bond policy, or `None` before its kind 38385
/// info event has been fetched (startup, node switch, or an unreachable node).
///
/// `None` and `Some(policy = Unsupported)` differ: the first is "not known
/// yet", the second is "known, and the daemon predates bonds".
Future<BondPolicyInfo?> getBondPolicy() =>
    RustLib.instance.api.crateApiBondGetBondPolicy();

/// Estimated bond the active node would ask for an order of
/// `order_amount_sats`, for the pre-commit warning. `None` when the policy is
/// unknown, not enabled, or advertises no percentage. Never used to charge
/// anything: the daemon sends the exact bolt11.
Future<BigInt?> estimateBondSats({required BigInt orderAmountSats}) => RustLib
    .instance
    .api
    .crateApiBondEstimateBondSats(orderAmountSats: orderAmountSats);

/// Walk away from an order parked at `WaitingMakerBond` without paying the
/// bond (docs/ANTI_ABUSE_BOND.md §6.2). The daemon refuses a cancel in this
/// window and reaps the unpaid order itself, so this only wipes the local
/// row and emits `Canceled` with `UserCanceled`. Markers: `TradeNotFound`,
/// `NotWaitingBond` when the row is not a maker's bond window.
Future<void> abandonBondedOrder({required String orderId}) =>
    RustLib.instance.api.crateApiBondAbandonBondedOrder(orderId: orderId);

/// Close the bond window of `order_id` now if its deadline passed unpaid —
/// what the periodic sweep would do on its next pass. The pay-bond screen
/// calls it when its countdown ends, so a row does not linger as "pay
/// deposit" in My Trades for up to a sweep interval. Returns whether the
/// row was closed; a paid, published or still-live window is left alone.
Future<bool> closeExpiredBondWindow({required String orderId}) =>
    RustLib.instance.api.crateApiBondCloseExpiredBondWindow(orderId: orderId);

/// Subscribe to claim phase changes (new claim, submission, ack, payout,
/// expiry).
Future<BondClaimStream> onBondClaimUpdated() =>
    RustLib.instance.api.crateApiBondOnBondClaimUpdated();

/// Every claim, most recently changed first (My Trades, §8.3).
Future<List<BondClaim>> listBondClaims() =>
    RustLib.instance.api.crateApiBondListBondClaims();

/// The claim for one order (the open one when several nodes issued one).
Future<BondClaim?> getBondClaim({required String orderId}) =>
    RustLib.instance.api.crateApiBondGetBondClaim(orderId: orderId);

/// The claim one node issued for one order — the exact claim a
/// [`BondClaimUpdate`] names, whatever other node holds one for the order.
Future<BondClaim?> getBondClaimFrom({
  required String nodePubkey,
  required String orderId,
}) => RustLib.instance.api.crateApiBondGetBondClaimFrom(
  nodePubkey: nodePubkey,
  orderId: orderId,
);

/// Send the daemon the bolt11 for a claim's share (§6.4): publish the
/// `add-bond-invoice` reply **to the node that issued the claim**, mark the
/// claim `Submitted` so the next cadence retry does not re-arm the form,
/// and wait for the daemon's verdict. Markers: `ClaimNotFound`,
/// `ClaimNotClaimable` (already acknowledged, paid or expired),
/// `InvalidInvoice`, `InvoiceAmountMismatch` (a decodable bolt11 for other
/// than the share), `TradeKeyMissing`, `BondClaimRejected` (a `CantDo`
/// the claim cannot explain; it stays `Pending`), `BondClaimExpired` (the
/// deadline passed), `NoDaemonResponse` (the claim stays `Submitted`; the
/// acknowledgement arrives on the global feed).
Future<void> submitBondPayoutInvoice({
  required String orderId,
  required String invoice,
}) => RustLib.instance.api.crateApiBondSubmitBondPayoutInvoice(
  orderId: orderId,
  invoice: invoice,
);

/// Subscribe to incoming `bond-slashed` notices.
Future<BondSlashedStream> onBondSlashed() =>
    RustLib.instance.api.crateApiBondOnBondSlashed();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BondClaimStream>>
abstract class BondClaimStream implements RustOpaqueInterface {
  /// The next claim change; a lag skips ahead rather than ending the stream.
  Future<BondClaimUpdate> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BondSlashedStream>>
abstract class BondSlashedStream implements RustOpaqueInterface {
  /// Poll for the next incoming bond-slashed notice.
  ///
  /// `RecvError::Lagged` is skipped gracefully rather than ending the stream.
  Future<BondSlashedEvent> next();
}
