// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `active_wallet`, `changes`, `ensure_enabled`, `lifecycle_lock`, `notify`, `proof_store_path`, `same_mint`, `sibling_store_path`, `snapshot`, `wallet_lock`

/// Connect the wallet to the mint the active node pins, unless already connected.
///
/// Lazy by design: nothing connects at startup, so a Lightning user never opens
/// a proof store or contacts a mint. Repeat calls are cheap — an already
/// connected wallet is returned as is rather than reconnected.
///
/// **Errors**: `CashuNotEnabled` when the node is not a usable Cashu node,
/// `NoIdentity` before an identity is loaded, `CashuNoMnemonic` for an
/// nsec-imported identity (there is no seed to derive), plus the markers from
/// [`CashuWallet::connect`].
Future<CashuWalletStatus> cashuConnect() =>
    RustLib.instance.api.crateApiCashuCashuConnect();

/// Current wallet status. Safe to call on any node — a Lightning node simply
/// reports "not connected".
Future<CashuWalletStatus> cashuStatus() =>
    RustLib.instance.api.crateApiCashuCashuStatus();

/// Spendable balance in satoshis.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`.
Future<BigInt> cashuGetBalance() =>
    RustLib.instance.api.crateApiCashuCashuGetBalance();

/// Redeem an encoded Cashu token into the wallet, returning the amount received.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuReceiveFailed`
/// (wrong mint, already spent, malformed).
Future<BigInt> cashuReceiveToken({required String encoded}) =>
    RustLib.instance.api.crateApiCashuCashuReceiveToken(encoded: encoded);

/// Export `amount_sats` from the wallet as an encoded token.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuAmountZero`,
/// `CashuSendFailed` (insufficient funds included).
Future<String> cashuCreateToken({required BigInt amountSats}) =>
    RustLib.instance.api.crateApiCashuCashuCreateToken(amountSats: amountSats);

/// Reconcile the proof store with the mint: proofs the mint reports spent are
/// forgotten, and the new balance is broadcast.
///
/// **Returns nothing on purpose.** It reclaims neither an unredeemed token of
/// ours nor the proofs of a half-finished send — cdk's state check cannot see
/// either — so there is no "reclaimed N sat" to report and C2 does not pretend
/// otherwise; see [`CashuWallet::sweep_spent_proofs`]. Getting an abandoned
/// token back is phase C10.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuMintChanged`.
Future<void> cashuSweepSpentProofs() =>
    RustLib.instance.api.crateApiCashuCashuSweepSpentProofs();

/// Drop the in-memory wallet. Proofs stay on disk — this is a disconnect, not a
/// wipe. Called when the active node changes, so a wallet bound to one node's
/// mint never serves another's.
Future<void> cashuDisconnect() =>
    RustLib.instance.api.crateApiCashuCashuDisconnect();

/// Subscribe to wallet changes.
Future<CashuWalletStream> onCashuWalletChanged() =>
    RustLib.instance.api.crateApiCashuOnCashuWalletChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CashuWalletStream>>
abstract class CashuWalletStream implements RustOpaqueInterface {
  /// Poll for the next wallet-changed event.
  ///
  /// A lagged receiver skips dropped snapshots: the value is current state,
  /// so only the newest one matters.
  Future<CashuWalletStatus> next();
}
