// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `acquire`, `blog_debug`, `blog_info`, `blog_warn`, `bridge_log`, `buffer_entry`, `buffer`, `default_max_level`, `display_relay`, `forward_log`, `log_sender`, `max_level_for`, `platform_console`, `sanitize_relay_text`, `scrub_secrets`, `set_verbose_logging`, `short_id`, `short_tag`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeLogger`, `ReentryGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `enabled`, `flush`, `log`

/// Install the log capture bridge. Called once from `init_app()`; until it
/// runs, `log::` records go nowhere.
Future<void> installLogBridge() =>
    RustLib.instance.api.crateApiLoggingInstallLogBridge();

/// Subscribe to the live log stream.
///
/// Each call returns an independent stream that only sees entries emitted
/// after it subscribes — pair it with [`recent_logs`] for history.
Future<LogEntryStream> onLogEntry() =>
    RustLib.instance.api.crateApiLoggingOnLogEntry();

/// Snapshot of the buffered history, newest first.
///
/// Ids increase monotonically: subscribe to [`on_log_entry`] first, snapshot
/// second, and drop streamed entries the snapshot already holds.
Future<List<LogEntry>> recentLogs() =>
    RustLib.instance.api.crateApiLoggingRecentLogs();

/// Drop the buffered history — log lines can name orders and counterparties,
/// so anything that wipes the user's identity should call this too.
Future<void> clearLogs() => RustLib.instance.api.crateApiLoggingClearLogs();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogEntryStream>>
abstract class LogEntryStream implements RustOpaqueInterface {
  /// Poll for the next log entry.
  Future<LogEntry?> next();
}
