// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `active_chats`, `add_message`, `admin_chat_context`, `advance_cursor`, `budget_ok`, `chat_context`, `chat_is_current`, `chat_still_relevant`, `chat_subscription_id`, `claim_chat`, `clear`, `cursor_key`, `ensure_durable`, `ensure_hydrated`, `forget_identity_chats`, `get_messages`, `guard_key`, `handle_chat_event`, `id_prefix`, `insert`, `is_known`, `is_supported_mime_type`, `load_chat_cursor`, `mark_as_read`, `message_store`, `message_type`, `mime_to_file_type`, `new`, `new`, `new`, `new`, `new`, `next_from`, `notification_backlog`, `notification_candidate_now`, `notification_candidate`, `parse_chat_payload`, `peer_to_wake`, `persist_decrypted_attachment`, `publish_chat_payload_for`, `publish_chat_payload`, `quota_exceeded`, `rebuild_session`, `reject`, `release_chat`, `resubscribe_active_chats`, `run_chat_subscription`, `safe_filename`, `session_or_rebuild`, `stop_chat_subscriptions`, `store_chat_cursor`, `store_outgoing_admin_message`, `subscribe_incoming_chat`, `try_take`, `unread_count_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BoundedIdSet`, `ChatChannel`, `ChatContext`, `ChatRxState`, `MessageStore`, `PublishedChat`, `TokenBucket`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Send an encrypted text message to the trade counterparty.
///
/// Validates that `content` is non-empty, wraps it in the chat envelope
/// (kind 14 signed with `K_sign`, inner kind 1 signed with the trade key) and
/// publishes it. If the session, peer, or relay pool is not available the
/// message is stored locally with a warning — same graceful degradation as
/// before, chat never throws for transport reasons.
///
/// Returns the sent `ChatMessage` (with `is_mine: true`).
Future<ChatMessage> sendMessage({
  required String tradeId,
  required String content,
}) => RustLib.instance.api.crateApiMessagesSendMessage(
  tradeId: tradeId,
  content: content,
);

/// Get all messages for a trade, ordered by creation time (oldest first).
Future<List<ChatMessage>> getMessages({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesGetMessages(tradeId: tradeId);

/// Mark all messages in a trade as read.
///
/// Emits on the `on_unread_count_changed` stream after updating.
Future<void> markAsRead({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesMarkAsRead(tradeId: tradeId);

/// Get total unread message count across all trades.
Future<int> getUnreadCount() =>
    RustLib.instance.api.crateApiMessagesGetUnreadCount();

/// Encrypt, upload, and send a file attachment.
///
/// Flow:
/// 1. Validate size (≤ 25 MB) and MIME type.
/// 2. Derive encryption key from ECDH shared key.
/// 3. Encrypt with ChaCha20-Poly1305 (`crate::crypto::file_enc`).
/// 4. Upload encrypted blob to Blossom server.
/// 5. Send Blossom URL + encryption metadata as NIP-59 message.
///
/// Returns the sent `ChatMessage` with `has_attachment: true`.
Future<ChatMessage> sendFile({
  required String tradeId,
  required List<int> fileBytes,
  required String fileName,
  required String mimeType,
}) => RustLib.instance.api.crateApiMessagesSendFile(
  tradeId: tradeId,
  fileBytes: fileBytes,
  fileName: fileName,
  mimeType: mimeType,
);

/// Download and decrypt a file attachment.
///
/// Returns a `FileDownloadResult` with the local path to the decrypted file.
Future<FileDownloadResult> downloadAttachment({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesDownloadAttachment(
      messageId: messageId,
    );

/// Get the attachment download status for a message.
Future<DownloadStatus?> getAttachmentStatus({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesGetAttachmentStatus(
      messageId: messageId,
    );

/// Stream that emits new messages for a specific trade.
Future<MessageStream> onNewMessage({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesOnNewMessage(tradeId: tradeId);

/// Incoming unread messages for notification cards, with at-least-once
/// delivery. Replays durable unread history on startup, channel lag and
/// every minute (including after resume), so a failed Dart persistence write
/// or a crash between the Rust and Dart commits is retried without a relay.
/// Consumers must deduplicate by message id, including deliberately suppressed
/// messages. Per-screen consumers want [`on_new_message`] instead.
Future<AnyMessageStream> onAnyNewMessage() =>
    RustLib.instance.api.crateApiMessagesOnAnyNewMessage();

/// Stream that emits the updated global unread count after any read/write.
Future<UnreadCountStream> onUnreadCountChanged() =>
    RustLib.instance.api.crateApiMessagesOnUnreadCountChanged();

/// Stream that emits attachment upload/download progress (0.0–1.0).
Future<AttachmentProgressStream> onAttachmentProgress({
  required String messageId,
}) => RustLib.instance.api.crateApiMessagesOnAttachmentProgress(
  messageId: messageId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AnyMessageStream>>
abstract class AnyMessageStream implements RustOpaqueInterface {
  Future<ChatMessage?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachmentProgressStream>>
abstract class AttachmentProgressStream implements RustOpaqueInterface {
  Future<double?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageStream>>
abstract class MessageStream implements RustOpaqueInterface {
  Future<ChatMessage?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnreadCountStream>>
abstract class UnreadCountStream implements RustOpaqueInterface {
  Future<int?> next();
}

/// Returned by `download_attachment`.
class FileDownloadResult {
  /// Absolute path to the decrypted file on the local device.
  final String localPath;
  final String fileName;
  final String mimeType;
  final BigInt fileSize;

  const FileDownloadResult({
    required this.localPath,
    required this.fileName,
    required this.mimeType,
    required this.fileSize,
  });

  @override
  int get hashCode =>
      localPath.hashCode ^
      fileName.hashCode ^
      mimeType.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileDownloadResult &&
          runtimeType == other.runtimeType &&
          localPath == other.localPath &&
          fileName == other.fileName &&
          mimeType == other.mimeType &&
          fileSize == other.fileSize;
}
