// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `apply_node_capabilities`, `apply_relay_list_event`, `default_relays`, `fetch_and_set_node_capabilities`, `generation_is_newer`, `get_pool`, `load_persisted_relays`, `new`, `note_relay_list_generation`, `on_pool_online`, `persist_relay`, `pool`, `relay_list_seen`, `relay_sync_tx`, `removal_effect`, `resync_with`, `run_resync`, `seed_default_relays`, `select_rates_event`, `tag_value`, `unpersist_relay`, `watch_connection_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ResyncState`

/// Initialize the Nostr client with a relay list.
///
/// If `relays` is empty or `None`, uses the persisted relay set — every
/// active relay the user or a Mostro node's kind 10002 list added, with the
/// user's removals of announced relays restored as the blacklist — and,
/// when nothing is persisted yet, the compiled-in defaults (which are then
/// seeded so later runs read them back).
Future<void> initialize({List<String>? relays}) =>
    RustLib.instance.api.crateApiNostrInitialize(relays: relays);

/// Add a new relay and connect to it.
Future<RelayInfo> addRelay({required String url}) =>
    RustLib.instance.api.crateApiNostrAddRelay(url: url);

/// Remove a relay and disconnect.
///
/// A relay a Mostro node announced stays persisted as blacklisted, so the
/// node's list cannot bring it back on the next start either.
Future<void> removeRelay({required String url}) =>
    RustLib.instance.api.crateApiNostrRemoveRelay(url: url);

/// Stream of relay URLs auto-added from the active node's kind 10002 relay
/// list, one emission per applied event (only when something was added).
Future<RelayAutoSyncStream> onRelayAutoSynced() =>
    RustLib.instance.api.crateApiNostrOnRelayAutoSynced();

/// Get all configured relays with current status.
Future<List<RelayInfo>> getRelays() =>
    RustLib.instance.api.crateApiNostrGetRelays();

/// Get overall connection state.
Future<ConnectionState> getConnectionState() =>
    RustLib.instance.api.crateApiNostrGetConnectionState();

/// Attempt to send all queued offline messages.
///
/// Iterates the in-memory outbox, publishes each pending event via the relay
/// pool, and applies exponential backoff on failure.  Events are pruned once
/// sent or after [`MAX_RETRIES`] failures.
///
/// Returns the count of messages successfully published in this pass.
Future<int> flushMessageQueue() =>
    RustLib.instance.api.crateApiNostrFlushMessageQueue();

/// Bring the core back in step with the relays after the process was
/// suspended (docs/PUSH_NOTIFICATIONS.md §10, issue #308).
///
/// The OS freezes the process wholesale and the sockets die with it; the
/// SDK reconnects on its own schedule, and nothing else re-checks that every
/// subscription survived or that the outbox drained. One pass, in order:
///
/// 1. **Reconnect nudge.** `connect()` spawns a connection task for every
///    relay that has none (a relay whose first attempt failed never got one)
///    and is a no-op for the rest; the wait is bounded, and the pool's own
///    state is what gets reported.
/// 2. **Subscriptions.** The bulk kind-14 filter is re-issued under its stable
///    id (the relay replaces it in place and replays the node's history; the
///    per-order status cursors keep that replay in order), the order-book
///    loop, the peer chats and the dispute chats are re-armed — each of them
///    a no-op when its task is alive. A pass that runs before the relays are
///    back lands its REQs nowhere; `nostr::live_subs` keeps the intent and
///    re-issues it on each relay as it connects.
/// 3. **Outbox.** Whatever was queued while offline is published.
///
/// Single-flight: concurrent calls coalesce onto the pass in progress and
/// report its outcome rather than starting another (`coalesced = true`).
/// Idempotent: a second pass over a healthy core changes nothing. Before the
/// pool exists (startup, tests) it reports offline and does nothing.
Future<ResyncOutcome> resync() => RustLib.instance.api.crateApiNostrResync();

/// Stream that emits when overall connection state changes.
Future<ConnectionStateStream> onConnectionStateChanged() =>
    RustLib.instance.api.crateApiNostrOnConnectionStateChanged();

/// Stream that emits when any individual relay's status changes.
Future<RelayStatusStream> onRelayStatusChanged() =>
    RustLib.instance.api.crateApiNostrOnRelayStatusChanged();

/// Fetch the Mostro daemon's Kind 38385 (instance status) tags.
///
/// Queries the relay pool for a Kind 38385 event published by `mostro_pubkey_hex`.
/// Returns the raw tag list as `Vec<Vec<String>>` so the Dart layer can parse
/// each tag into the `MostroInstance` model.
///
/// Returns `None` if no matching event arrives within 10 seconds (relay
/// not reachable, or daemon has never published a Kind 38385 event).
Future<List<List<String>>?> fetchMostroInstanceTags({
  required String mostroPubkeyHex,
}) => RustLib.instance.api.crateApiNostrFetchMostroInstanceTags(
  mostroPubkeyHex: mostroPubkeyHex,
);

/// Price of one BTC in `fiat_code`, as published by `mostro_pubkey_hex` in its
/// Kind 30078 (`d` = `mostro-rates`) event.
///
/// Lets the client tell, before submitting, whether a market-price order will
/// land inside the node's sats limits (#337): the daemon prices such an order
/// as `fiat_amount / price * 1E8` from this same aggregate, so this is the
/// number its `OutOfRangeSatsAmount` check will use.
///
/// Returns `None` — never an error — for every "no usable rate" case: the node
/// publishes no rates event (publishing is optional), the one on the relay has
/// expired, its payload is unusable, or it quotes no such currency. Callers
/// must then submit unchecked and let the daemon decide, which is the
/// fail-open behaviour PR #302 chose for fixed-sats amounts. `Err` is reserved
/// for a client that is not initialised, a malformed pubkey, or a relay query
/// that failed outright.
///
/// Answers from a per-node cache bounded by the event's own NIP-40 expiration,
/// so the three amount fields of a range order cost one relay query, not three.
Future<double?> fetchExchangeRate({
  required String mostroPubkeyHex,
  required String fiatCode,
}) => RustLib.instance.api.crateApiNostrFetchExchangeRate(
  mostroPubkeyHex: mostroPubkeyHex,
  fiatCode: fiatCode,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionStateStream>>
abstract class ConnectionStateStream implements RustOpaqueInterface {
  Future<ConnectionState?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RelayAutoSyncStream>>
abstract class RelayAutoSyncStream implements RustOpaqueInterface {
  Future<List<String>?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RelayStatusStream>>
abstract class RelayStatusStream implements RustOpaqueInterface {
  Future<RelayInfo?> next();
}
