// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `notify`, `wallet_store`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WalletStore`

/// Parse and connect a NWC wallet.
///
/// **URI format**: `nostr+walletconnect://<pubkey>?relay=<url>&secret=<hex>`
///
/// Validates the URI, creates an [NwcClient], calls `get_info()` to confirm
/// connectivity, and stores the client in memory.
///
/// **Errors**: `InvalidNwcUri`, `ConnectionFailed`.
Future<NwcWalletInfo> connectWallet({required String nwcUri}) =>
    RustLib.instance.api.crateApiNwcConnectWallet(nwcUri: nwcUri);

/// Disconnect the current wallet and clear stored credentials.
///
/// **Errors**: `NoWalletConnected`.
Future<void> disconnectWallet() =>
    RustLib.instance.api.crateApiNwcDisconnectWallet();

/// Return current wallet info, or `None` if no wallet is connected.
Future<NwcWalletInfo?> getWallet() =>
    RustLib.instance.api.crateApiNwcGetWallet();

/// Query wallet balance in satoshis (live from the wallet, not cached).
///
/// **Errors**: `NoWalletConnected`, `WalletError`.
Future<BigInt?> getBalance() => RustLib.instance.api.crateApiNwcGetBalance();

/// Pay a BOLT-11 invoice via the connected NWC wallet.
///
/// **Errors**: `NoWalletConnected`, `InvoiceInvalid`.
Future<PaymentResult> payInvoice({required String bolt11}) =>
    RustLib.instance.api.crateApiNwcPayInvoice(bolt11: bolt11);

/// Request the wallet to create a new Lightning invoice.
///
/// `amount_sats` is the invoice amount in satoshis (converted to msats
/// for the NIP-47 request).  Returns the BOLT-11 invoice string.
///
/// **Errors**: `NoWalletConnected`, `WalletError`.
Future<String> makeInvoice({required BigInt amountSats, String? description}) =>
    RustLib.instance.api.crateApiNwcMakeInvoice(
      amountSats: amountSats,
      description: description,
    );

/// Subscribe to wallet status changes.
Future<WalletStatusStream> onWalletStatusChanged() =>
    RustLib.instance.api.crateApiNwcOnWalletStatusChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletStatusStream>>
abstract class WalletStatusStream implements RustOpaqueInterface {
  /// Poll for the next wallet status change.
  ///
  /// `RecvError::Lagged` is handled gracefully.
  Future<NwcWalletInfo?> next();
}
