// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `classify`, `clear_node_refusal`, `client`, `current_wanted`, `emit_status`, `issuing_nodes_of_live_trades`, `last_notify`, `last_report`, `load_state`, `mirror_path`, `note_failure`, `notify_peer_with`, `post`, `production_server`, `reconcile_core`, `reconcile_with`, `request_reconcile`, `save_registrations`, `start_push_timer`, `status_of`, `status_tx`, `unregister_all`, `wake_peer`, `write_mirror`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HttpPushServer`, `NotifyOutcome`, `PushState`, `ReconcileReport`, `ServerOutcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `notify`, `register`, `unregister`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `notify`, `register`, `unregister`

/// Bring what the push server holds in step with what is wanted, now.
/// Single-flight: a pass in progress finishes first, and a request that
/// arrived meanwhile makes it run again rather than in parallel. Nothing
/// here fails: every outcome is logged and reflected in [`get_push_status`].
Future<void> reconcilePush() =>
    RustLib.instance.api.crateApiPushReconcilePush();

/// Dart hands the device token over (first token, and every refresh).
Future<void> setPushToken({
  required String token,
  required PushPlatform platform,
}) => RustLib.instance.api.crateApiPushSetPushToken(
  token: token,
  platform: platform,
);

/// After `deleteToken()` on the device: nothing can be registered any more.
Future<void> clearPushToken() =>
    RustLib.instance.api.crateApiPushClearPushToken();

/// The master toggle. Off unregisters everything the persisted state knows
/// about, whichever run registered it; on clears every node refusal (the
/// user's "try again") and registers the current set.
Future<void> setPushEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiPushSetPushEnabled(enabled: enabled);

/// What Settings shows. Reads the persisted state, so it is right after a
/// restart before any reconcile ran.
Future<PushStatus> getPushStatus() =>
    RustLib.instance.api.crateApiPushGetPushStatus();

Future<PushStatusStream> onPushStatusChanged() =>
    RustLib.instance.api.crateApiPushOnPushStatusChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PushStatusStream>>
abstract class PushStatusStream implements RustOpaqueInterface {
  /// The next status; a lag skips ahead rather than ending the stream.
  Future<PushStatus> next();
}
