// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ask`, `check_exported`, `check_importable`, `event_id`, `identity_keys`, `is_export_reply`, `is_import_reply`, `new`, `parse`, `pending_slot`, `pubkey`, `refusal`, `same_identity`, `while_still_current`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// What the active node advertises, as of its last capability fetch.
ReputationSupportInfo getReputationSupport() =>
    RustLib.instance.api.crateApiReputationTransferGetReputationSupport();

/// Verify an attestation pasted or received, without sending anything: the
/// event's own rules (signature, kind, tags, clock). Whether the node trusts
/// its issuer is the node's to say on import.
ReputationAttestationInfo parseReputationAttestation({required String json}) =>
    RustLib.instance.api.crateApiReputationTransferParseReputationAttestation(
      json: json,
    );

/// Ask the active node to attest the user's reputation there for
/// `destination` (the user's own identity when `None`). The UI confirms the
/// destination with the user first: the request binds the node's account to
/// it. `rebind` is an authorisation from [`sign_reputation_rebind`], needed
/// when the account is bound to another identity. The attestation is
/// verified, kept until imported, and returned.
Future<ReputationAttestationInfo> exportReputation({
  String? destination,
  String? rebind,
}) => RustLib.instance.api.crateApiReputationTransferExportReputation(
  destination: destination,
  rebind: rebind,
);

/// Import `attestation_json` into the active node. It must name the user's
/// identity and be signed by a key the node advertises it trusts; the node
/// runs the full checks and answers `reputation-imported` or a refusal.
Future<ReputationAttestationInfo> importReputation({
  required String attestationJson,
}) => RustLib.instance.api.crateApiReputationTransferImportReputation(
  attestationJson: attestationJson,
);

/// The attestation exported last and not imported yet, while still valid.
/// One slot for all nodes: a later export replaces it. An expired one is
/// dropped; one refused for another reason (a clock behind the issuer's)
/// is kept, as it may verify later.
Future<ReputationAttestationInfo?> getPendingReputationAttestation() =>
    RustLib.instance.api
        .crateApiReputationTransferGetPendingReputationAttestation();

/// Sign, with the identity the reputation at `issuer` is bound to now, the
/// authorisation to move that binding to `new_identity` (hex). Pass it as
/// `rebind` to [`export_reputation`] from the new identity, or paste it into
/// lnp2pBot. Valid for an hour.
Future<String> signReputationRebind({
  required String issuer,
  required String newIdentity,
}) => RustLib.instance.api.crateApiReputationTransferSignReputationRebind(
  issuer: issuer,
  newIdentity: newIdentity,
);

/// A verified reputation attestation, for display and import.
class ReputationAttestationInfo {
  final String id;

  /// Key that signed it.
  final String issuer;

  /// Identity it is addressed to.
  final String destination;

  /// The source account, opaque.
  final String subject;

  /// Ratings received on the source.
  final int reviews;

  /// Their average, with two decimals (`"4.87"`).
  final String rating;

  /// UTC day start of the first completed trade on the source.
  final PlatformInt64 since;
  final PlatformInt64 createdAt;
  final PlatformInt64 expiration;

  /// The event JSON, as received, to import unchanged.
  final String json;

  const ReputationAttestationInfo({
    required this.id,
    required this.issuer,
    required this.destination,
    required this.subject,
    required this.reviews,
    required this.rating,
    required this.since,
    required this.createdAt,
    required this.expiration,
    required this.json,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      issuer.hashCode ^
      destination.hashCode ^
      subject.hashCode ^
      reviews.hashCode ^
      rating.hashCode ^
      since.hashCode ^
      createdAt.hashCode ^
      expiration.hashCode ^
      json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReputationAttestationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          issuer == other.issuer &&
          destination == other.destination &&
          subject == other.subject &&
          reviews == other.reviews &&
          rating == other.rating &&
          since == other.since &&
          createdAt == other.createdAt &&
          expiration == other.expiration &&
          json == other.json;
}

/// What the active node offers for reputation portability.
class ReputationSupportInfo {
  /// The key the node signs attestations with; `None` when it does not
  /// export.
  final String? issuer;

  /// The issuer keys it imports from; `None` when it does not import.
  final List<String>? importIssuers;

  const ReputationSupportInfo({this.issuer, this.importIssuers});

  @override
  int get hashCode => issuer.hashCode ^ importIssuers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReputationSupportInfo &&
          runtimeType == other.runtimeType &&
          issuer == other.issuer &&
          importIssuers == other.importIssuers;
}
